### PR TITLE
Replace `p6sgi` with `p6w`

### PR DESCRIPTION
**Pull request by tokuhirom**

### CODE REVIEW

**Comment by tokuhirom** [comment]
@skaji could you review again?

**Comment by skaji** [comment]
* Should we rename t/HTTP-Message-PSGI to t/HTTP-Message-P6W ?
* The following files still use the word "psgi":
  * t/HTTP-Message-PSGI/res.t  
  * lib/HTTP/Message/P6W.pm6 (in pod)
  * lib/Crust/Request.pm6 (in comment)

**Comment by tokuhirom** [comment]
@skaji fixed!

**Comment by skaji** [comment]
LGTM!

**Pull request merged**
