### PR TITLE
Add Crust::Middleware::ReverseProxy

### PR DESCRIPTION
**Pull request by moznion**

### CODE REVIEW

**Comment by moznion** [comment]
I'm waiting for the fixing http-useragent!!
https://github.com/sergot/http-useragent/compare/master...shoichikaji:patch-1

**Comment by shoichikaji** [comment]
The following dirty patch saves us :)
```diff
diff --git t/Crust-Middleware/reverse-proxy.t t/Crust-Middleware/reverse-proxy.t
index 222c2b4..9ffd7bf 100644
--- t/Crust-Middleware/reverse-proxy.t
+++ t/Crust-Middleware/reverse-proxy.t
@@ -15,6 +15,10 @@ sub run(Str $tag, %arg) {
                 GET => 'http://example.com/?foo=bar',
                 |%input,
             );
+            # FIXME: overwrite http header 'Host'
+            if %input.keys.first({.lc eq "host"}) -> $host {
+                $req.field(Host => %input{$host});
+            }
             my $res = $cb($req);
         },
         app => -> %env {
```

**Comment by moznion** [comment]
Wow!

**Comment by tokuhirom** [comment]
Should we validate REMOTE_ADDR?

**Comment by moznion** [comment]
Probably yes.
`rx{\d ** 1..3 '.' \d ** 1..3 '.' \d ** 1..3 '.' \d ** 1..3}` ?

**Comment by tokuhirom** [comment]
It should be configurable.

**Comment by moznion** [comment]
Got it

**Comment by moznion** [comment]
new: https://github.com/tokuhirom/p6-Crust/pull/25

**Pull request closed without merging**
