### PR TITLE
Fix urlmap

### PR DESCRIPTION
**Pull request by shoichikaji**
We should do `$path !~~ s/^ $loc //`.
See https://github.com/plack/Plack/blob/master/lib/Plack/App/URLMap.pm#L59

### CODE REVIEW

**Comment by tokuhirom** [comment]
could you rebase this p-r?

**Comment by mattn** [comment]
@tokuhirom done

**Comment by tokuhirom** [comment]
waiting pr

**Comment by mattn** [comment]
@shoichikaji thanks!

**Pull request merged**
